# 시재 관리
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QDoubleValidator, QIntValidator

# QtDesigner를 통해 생성한 UI 폼
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 900)
        Form.setMinimumSize(QtCore.QSize(1500, 900))
        Form.setMaximumSize(QtCore.QSize(1500, 900))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timeLabel = QtWidgets.QLabel(Form)
        self.timeLabel.setMinimumSize(QtCore.QSize(170, 100))
        self.timeLabel.setMaximumSize(QtCore.QSize(170, 100))
        self.timeLabel.setStyleSheet("font: 75 15pt \"함초롬돋움\";")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_2.addWidget(self.timeLabel)
        self.timeBox = QtWidgets.QTextEdit()
        self.timeBox.setStyleSheet("font: 75 15pt \"함초롬돋움\";")
        self.timeBox.setReadOnly(True)
        self.timeBox.setMinimumSize(QtCore.QSize(300, 100))
        self.timeBox.setMaximumSize(QtCore.QSize(300, 100))
        self.timeBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timeBox.setObjectName("timeBox")
        self.horizontalLayout_2.addWidget(self.timeBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.goBackBtn = QtWidgets.QPushButton(Form)
        self.goBackBtn.setMinimumSize(QtCore.QSize(230, 103))
        self.goBackBtn.setMaximumSize(QtCore.QSize(230, 100))
        self.goBackBtn.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.goBackBtn.setObjectName("goBackBtn")
        self.horizontalLayout.addWidget(self.goBackBtn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 59, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.moneyLabel50000 = QtWidgets.QLabel(Form)
        self.moneyLabel50000.setMinimumSize(QtCore.QSize(180, 50))
        self.moneyLabel50000.setMaximumSize(QtCore.QSize(180, 50))
        self.moneyLabel50000.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyLabel50000.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyLabel50000.setObjectName("moneyLabel50000")
        self.verticalLayout_3.addWidget(self.moneyLabel50000)
        self.moneyBox50000 = QtWidgets.QLineEdit(Form)
        self.onlyNum = QIntValidator()
        self.moneyBox50000.setValidator(self.onlyNum)
        self.moneyBox50000.setText('0')
        self.moneyBox50000.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyBox50000.setMinimumSize(QtCore.QSize(180, 80))
        self.moneyBox50000.setMaximumSize(QtCore.QSize(180, 80))
        self.moneyBox50000.setObjectName("moneyBox50000")
        self.verticalLayout_3.addWidget(self.moneyBox50000)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.moneyLabel10000 = QtWidgets.QLabel(Form)
        self.moneyLabel10000.setMinimumSize(QtCore.QSize(180, 50))
        self.moneyLabel10000.setMaximumSize(QtCore.QSize(180, 50))
        self.moneyLabel10000.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyLabel10000.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyLabel10000.setObjectName("moneyLabel10000")
        self.verticalLayout_5.addWidget(self.moneyLabel10000)
        self.moneyBox10000 = QtWidgets.QLineEdit(Form)
        self.moneyBox10000.setValidator(self.onlyNum)
        self.moneyBox10000.setText('0')
        self.moneyBox10000.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyBox10000.setMinimumSize(QtCore.QSize(180, 80))
        self.moneyBox10000.setMaximumSize(QtCore.QSize(180, 80))
        self.moneyBox10000.setObjectName("moneyBox10000")
        self.verticalLayout_5.addWidget(self.moneyBox10000)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.moneyLabel5000 = QtWidgets.QLabel(Form)
        self.moneyLabel5000.setMinimumSize(QtCore.QSize(180, 50))
        self.moneyLabel5000.setMaximumSize(QtCore.QSize(180, 50))
        self.moneyLabel5000.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyLabel5000.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyLabel5000.setObjectName("moneyLabel5000")
        self.verticalLayout_6.addWidget(self.moneyLabel5000)
        self.moneyBox5000 = QtWidgets.QLineEdit(Form)
        self.moneyBox5000.setValidator(self.onlyNum)
        self.moneyBox5000.setText('0')
        self.moneyBox5000.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyBox5000.setMinimumSize(QtCore.QSize(180, 80))
        self.moneyBox5000.setMaximumSize(QtCore.QSize(180, 80))
        self.moneyBox5000.setObjectName("moneyBox5000")
        self.verticalLayout_6.addWidget(self.moneyBox5000)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.moneyLabel1000 = QtWidgets.QLabel(Form)
        self.moneyLabel1000.setMinimumSize(QtCore.QSize(180, 50))
        self.moneyLabel1000.setMaximumSize(QtCore.QSize(180, 50))
        self.moneyLabel1000.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyLabel1000.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyLabel1000.setObjectName("moneyLabel1000")
        self.verticalLayout_7.addWidget(self.moneyLabel1000)
        self.moneyBox1000 = QtWidgets.QLineEdit(Form)
        self.moneyBox1000.setValidator(self.onlyNum)
        self.moneyBox1000.setText('0')
        self.moneyBox1000.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyBox1000.setMinimumSize(QtCore.QSize(180, 80))
        self.moneyBox1000.setMaximumSize(QtCore.QSize(180, 80))
        self.moneyBox1000.setObjectName("moneyBox1000")
        self.verticalLayout_7.addWidget(self.moneyBox1000)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.moneyLabel500 = QtWidgets.QLabel(Form)
        self.moneyLabel500.setMinimumSize(QtCore.QSize(180, 50))
        self.moneyLabel500.setMaximumSize(QtCore.QSize(180, 50))
        self.moneyLabel500.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyLabel500.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyLabel500.setObjectName("moneyLabel500")
        self.verticalLayout_8.addWidget(self.moneyLabel500)
        self.moneyBox500 = QtWidgets.QLineEdit(Form)
        self.moneyBox500.setValidator(self.onlyNum)
        self.moneyBox500.setText('0')
        self.moneyBox500.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyBox500.setMinimumSize(QtCore.QSize(180, 80))
        self.moneyBox500.setMaximumSize(QtCore.QSize(180, 80))
        self.moneyBox500.setObjectName("moneyBox500")
        self.verticalLayout_8.addWidget(self.moneyBox500)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.moneyLabel100 = QtWidgets.QLabel(Form)
        self.moneyLabel100.setMinimumSize(QtCore.QSize(180, 50))
        self.moneyLabel100.setMaximumSize(QtCore.QSize(180, 50))
        self.moneyLabel100.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyLabel100.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyLabel100.setObjectName("moneyLabel100")
        self.verticalLayout_9.addWidget(self.moneyLabel100)
        self.moneyBox100 = QtWidgets.QLineEdit(Form)
        self.moneyBox100.setValidator(self.onlyNum)
        self.moneyBox100.setText('0')
        self.moneyBox100.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyBox100.setMinimumSize(QtCore.QSize(180, 80))
        self.moneyBox100.setMaximumSize(QtCore.QSize(180, 80))
        self.moneyBox100.setObjectName("moneyBox100")
        self.verticalLayout_9.addWidget(self.moneyBox100)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.moneyLabel50 = QtWidgets.QLabel(Form)
        self.moneyLabel50.setMinimumSize(QtCore.QSize(180, 50))
        self.moneyLabel50.setMaximumSize(QtCore.QSize(180, 50))
        self.moneyLabel50.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyLabel50.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyLabel50.setObjectName("moneyLabel50")
        self.verticalLayout_10.addWidget(self.moneyLabel50)
        self.moneyBox50 = QtWidgets.QLineEdit(Form)
        self.moneyBox50.setValidator(self.onlyNum)
        self.moneyBox50.setText('0')
        self.moneyBox50.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyBox50.setMinimumSize(QtCore.QSize(180, 80))
        self.moneyBox50.setMaximumSize(QtCore.QSize(180, 80))
        self.moneyBox50.setObjectName("moneyBox50")
        self.verticalLayout_10.addWidget(self.moneyBox50)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.moneyBox10_2 = QtWidgets.QLabel(Form)
        self.moneyBox10_2.setMinimumSize(QtCore.QSize(180, 50))
        self.moneyBox10_2.setMaximumSize(QtCore.QSize(180, 50))
        self.moneyBox10_2.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyBox10_2.setAlignment(QtCore.Qt.AlignCenter)
        self.moneyBox10_2.setObjectName("moneyBox10_2")
        self.verticalLayout_11.addWidget(self.moneyBox10_2)
        self.moneyBox10 = QtWidgets.QLineEdit(Form)
        self.moneyBox10.setValidator(self.onlyNum)
        self.moneyBox10.setText('0')
        self.moneyBox10.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.moneyBox10.setMinimumSize(QtCore.QSize(180, 80))
        self.moneyBox10.setMaximumSize(QtCore.QSize(180, 80))
        self.moneyBox10.setObjectName("moneyBox10")
        self.verticalLayout_11.addWidget(self.moneyBox10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.beforeLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.beforeLabel.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.beforeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.beforeLabel.setObjectName("beforeLabel")
        self.horizontalLayout_3.addWidget(self.beforeLabel)
        self.beforeBox = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.beforeBox.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.onlyDouble = QDoubleValidator()
        self.beforeBox.setValidator(self.onlyDouble)
        self.beforeBox.setMinimumSize(QtCore.QSize(400, 100))
        self.beforeBox.setMaximumSize(QtCore.QSize(400, 100))
        self.beforeBox.setObjectName("beforeBox")
        self.horizontalLayout_3.addWidget(self.beforeBox)
        self.wonLabel1 = QtWidgets.QLabel(self.layoutWidget_2)
        self.wonLabel1.setMinimumSize(QtCore.QSize(100, 80))
        self.wonLabel1.setMaximumSize(QtCore.QSize(100, 80))
        self.wonLabel1.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.wonLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.wonLabel1.setObjectName("wonLabel1")
        self.horizontalLayout_3.addWidget(self.wonLabel1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.afterLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.afterLabel.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.afterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.afterLabel.setObjectName("afterLabel")
        self.horizontalLayout_4.addWidget(self.afterLabel)
        self.afterBox = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.afterBox.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.afterBox.setValidator(self.onlyDouble)
        self.afterBox.setMinimumSize(QtCore.QSize(400, 100))
        self.afterBox.setMaximumSize(QtCore.QSize(400, 100))
        self.afterBox.setObjectName("afterBox")
        self.horizontalLayout_4.addWidget(self.afterBox)
        self.wonLabel2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.wonLabel2.setMinimumSize(QtCore.QSize(100, 80))
        self.wonLabel2.setMaximumSize(QtCore.QSize(100, 80))
        self.wonLabel2.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.wonLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.wonLabel2.setObjectName("wonLabel2")
        self.horizontalLayout_4.addWidget(self.wonLabel2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.errorLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.errorLabel.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.horizontalLayout_5.addWidget(self.errorLabel)
        self.errorBox = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.errorBox.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.errorBox.setValidator(self.onlyDouble)
        self.errorBox.setMinimumSize(QtCore.QSize(400, 100))
        self.errorBox.setMaximumSize(QtCore.QSize(400, 100))
        self.errorBox.setObjectName("errorBox")
        self.horizontalLayout_5.addWidget(self.errorBox)
        self.wonLabel3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.wonLabel3.setMinimumSize(QtCore.QSize(100, 80))
        self.wonLabel3.setMaximumSize(QtCore.QSize(100, 80))
        self.wonLabel3.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.wonLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.wonLabel3.setObjectName("wonLabel3")
        self.horizontalLayout_5.addWidget(self.wonLabel3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchBtn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.searchBtn.setMinimumSize(QtCore.QSize(300, 100))
        self.searchBtn.setMaximumSize(QtCore.QSize(300, 100))
        self.searchBtn.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.searchBtn.setObjectName("searchBtn")
        self.verticalLayout_2.addWidget(self.searchBtn)
        self.cashAvailableBtn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.cashAvailableBtn.setMinimumSize(QtCore.QSize(300, 100))
        self.cashAvailableBtn.setMaximumSize(QtCore.QSize(300, 100))
        self.cashAvailableBtn.setStyleSheet("font: 75 20pt \"함초롬돋움\";")
        self.cashAvailableBtn.setObjectName("cashAvailableBtn")
        self.verticalLayout_2.addWidget(self.cashAvailableBtn)
        self.horizontalLayout_7.addWidget(self.splitter)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 59, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.timeLabel.setText(_translate("Form", "현재 시각: "))
        self.goBackBtn.setText(_translate("Form", "돌아가기"))
        self.moneyLabel50000.setText(_translate("Form", "5만원"))
        self.moneyLabel10000.setText(_translate("Form", "1만원"))
        self.moneyLabel5000.setText(_translate("Form", "5천원"))
        self.moneyLabel1000.setText(_translate("Form", "1천원"))
        self.moneyLabel500.setText(_translate("Form", "500원"))
        self.moneyLabel100.setText(_translate("Form", "100원"))
        self.moneyLabel50.setText(_translate("Form", "50원"))
        self.moneyBox10_2.setText(_translate("Form", "10원"))
        self.beforeLabel.setText(_translate("Form", "시재"))
        self.wonLabel1.setText(_translate("Form", "원"))
        self.afterLabel.setText(_translate("Form", "현재 금액"))
        self.wonLabel2.setText(_translate("Form", "원"))
        self.errorLabel.setText(_translate("Form", "차액"))
        self.wonLabel3.setText(_translate("Form", "원"))
        self.searchBtn.setText(_translate("Form", "조회"))
        self.cashAvailableBtn.setText(_translate("Form", "정산"))

