# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'productStat.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 900)
        Form.setMinimumSize(QtCore.QSize(1500, 900))
        Form.setMaximumSize(QtCore.QSize(1500, 900))
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 240, 901, 651))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 899, 649))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.viewBox = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.viewBox.setGeometry(QtCore.QRect(10, 110, 881, 531))
        self.viewBox.setObjectName("viewBox")
        self.layoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 0, 806, 102))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tableBtn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.tableBtn.setMinimumSize(QtCore.QSize(400, 100))
        self.tableBtn.setMaximumSize(QtCore.QSize(400, 100))
        self.tableBtn.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.tableBtn.setObjectName("tableBtn")
        self.horizontalLayout_7.addWidget(self.tableBtn)
        self.graphBtn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.graphBtn.setMinimumSize(QtCore.QSize(400, 100))
        self.graphBtn.setMaximumSize(QtCore.QSize(400, 100))
        self.graphBtn.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.graphBtn.setObjectName("graphBtn")
        self.horizontalLayout_7.addWidget(self.graphBtn)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(370, 80, 201, 261))
        self.widget.setObjectName("widget")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setGeometry(QtCore.QRect(920, 260, 581, 631))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dailySalesLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dailySalesLabel.setMinimumSize(QtCore.QSize(150, 80))
        self.dailySalesLabel.setMaximumSize(QtCore.QSize(150, 80))
        self.dailySalesLabel.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.dailySalesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dailySalesLabel.setObjectName("dailySalesLabel")
        self.horizontalLayout_4.addWidget(self.dailySalesLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.dailySalesBox = QtWidgets.QTextBrowser(self.splitter)
        self.dailySalesBox.setMinimumSize(QtCore.QSize(450, 100))
        self.dailySalesBox.setMaximumSize(QtCore.QSize(450, 100))
        self.dailySalesBox.setObjectName("dailySalesBox")
        self.wonLabel1 = QtWidgets.QLabel(self.splitter)
        self.wonLabel1.setMinimumSize(QtCore.QSize(100, 100))
        self.wonLabel1.setMaximumSize(QtCore.QSize(100, 100))
        self.wonLabel1.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.wonLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.wonLabel1.setObjectName("wonLabel1")
        self.verticalLayout.addWidget(self.splitter)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.monthlySalesLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.monthlySalesLabel.setMinimumSize(QtCore.QSize(150, 80))
        self.monthlySalesLabel.setMaximumSize(QtCore.QSize(150, 80))
        self.monthlySalesLabel.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.monthlySalesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.monthlySalesLabel.setObjectName("monthlySalesLabel")
        self.horizontalLayout_5.addWidget(self.monthlySalesLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.splitter_3 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.monthlySalesBox = QtWidgets.QTextBrowser(self.splitter_3)
        self.monthlySalesBox.setMinimumSize(QtCore.QSize(450, 100))
        self.monthlySalesBox.setMaximumSize(QtCore.QSize(450, 100))
        self.monthlySalesBox.setObjectName("monthlySalesBox")
        self.wonLabel2 = QtWidgets.QLabel(self.splitter_3)
        self.wonLabel2.setMinimumSize(QtCore.QSize(100, 100))
        self.wonLabel2.setMaximumSize(QtCore.QSize(100, 100))
        self.wonLabel2.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.wonLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.wonLabel2.setObjectName("wonLabel2")
        self.verticalLayout_2.addWidget(self.splitter_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.yearSalesLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.yearSalesLabel.setMinimumSize(QtCore.QSize(150, 80))
        self.yearSalesLabel.setMaximumSize(QtCore.QSize(150, 80))
        self.yearSalesLabel.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.yearSalesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yearSalesLabel.setObjectName("yearSalesLabel")
        self.horizontalLayout_6.addWidget(self.yearSalesLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.splitter_4 = QtWidgets.QSplitter(self.layoutWidget2)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.yearSalesBox = QtWidgets.QTextBrowser(self.splitter_4)
        self.yearSalesBox.setMinimumSize(QtCore.QSize(450, 100))
        self.yearSalesBox.setMaximumSize(QtCore.QSize(450, 100))
        self.yearSalesBox.setObjectName("yearSalesBox")
        self.wonLabel3 = QtWidgets.QLabel(self.splitter_4)
        self.wonLabel3.setMinimumSize(QtCore.QSize(100, 100))
        self.wonLabel3.setMaximumSize(QtCore.QSize(100, 100))
        self.wonLabel3.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.wonLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.wonLabel3.setObjectName("wonLabel3")
        self.verticalLayout_3.addWidget(self.splitter_4)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(10, 120, 1471, 111))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chickenBtn = QtWidgets.QPushButton(self.widget1)
        self.chickenBtn.setMinimumSize(QtCore.QSize(400, 100))
        self.chickenBtn.setMaximumSize(QtCore.QSize(400, 100))
        self.chickenBtn.setStyleSheet("font: 75 35pt \"함초롬돋움\";\n"
"background-color: rgb(252, 190, 113);")
        self.chickenBtn.setObjectName("chickenBtn")
        self.horizontalLayout_3.addWidget(self.chickenBtn)
        self.beverageBtn = QtWidgets.QPushButton(self.widget1)
        self.beverageBtn.setMinimumSize(QtCore.QSize(400, 100))
        self.beverageBtn.setMaximumSize(QtCore.QSize(400, 100))
        self.beverageBtn.setStyleSheet("font: 75 35pt \"함초롬돋움\";\n"
"background-color: rgb(85, 201, 234);")
        self.beverageBtn.setObjectName("beverageBtn")
        self.horizontalLayout_3.addWidget(self.beverageBtn)
        self.othersBtn = QtWidgets.QPushButton(self.widget1)
        self.othersBtn.setMinimumSize(QtCore.QSize(400, 100))
        self.othersBtn.setMaximumSize(QtCore.QSize(400, 100))
        self.othersBtn.setStyleSheet("font: 75 35pt \"함초롬돋움\";\n"
"background-color: rgb(159, 217, 111);")
        self.othersBtn.setObjectName("othersBtn")
        self.horizontalLayout_3.addWidget(self.othersBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(10, 10, 1472, 102))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeLabel = QtWidgets.QLabel(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeLabel.sizePolicy().hasHeightForWidth())
        self.timeLabel.setSizePolicy(sizePolicy)
        self.timeLabel.setMinimumSize(QtCore.QSize(170, 100))
        self.timeLabel.setMaximumSize(QtCore.QSize(170, 100))
        self.timeLabel.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel)
        self.timeBox = QtWidgets.QTextBrowser(self.widget2)
        self.timeBox.setMinimumSize(QtCore.QSize(200, 50))
        self.timeBox.setMaximumSize(QtCore.QSize(200, 50))
        self.timeBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timeBox.setObjectName("timeBox")
        self.horizontalLayout.addWidget(self.timeBox)
        self.dateStatBtn = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateStatBtn.sizePolicy().hasHeightForWidth())
        self.dateStatBtn.setSizePolicy(sizePolicy)
        self.dateStatBtn.setMinimumSize(QtCore.QSize(280, 100))
        self.dateStatBtn.setMaximumSize(QtCore.QSize(250, 100))
        self.dateStatBtn.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.dateStatBtn.setObjectName("dateStatBtn")
        self.horizontalLayout.addWidget(self.dateStatBtn)
        self.productManagementBtn = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productManagementBtn.sizePolicy().hasHeightForWidth())
        self.productManagementBtn.setSizePolicy(sizePolicy)
        self.productManagementBtn.setMinimumSize(QtCore.QSize(280, 100))
        self.productManagementBtn.setMaximumSize(QtCore.QSize(250, 100))
        self.productManagementBtn.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.productManagementBtn.setObjectName("productManagementBtn")
        self.horizontalLayout.addWidget(self.productManagementBtn)
        self.cashAvailableBtn = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cashAvailableBtn.sizePolicy().hasHeightForWidth())
        self.cashAvailableBtn.setSizePolicy(sizePolicy)
        self.cashAvailableBtn.setMinimumSize(QtCore.QSize(260, 100))
        self.cashAvailableBtn.setMaximumSize(QtCore.QSize(260, 100))
        self.cashAvailableBtn.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.cashAvailableBtn.setObjectName("cashAvailableBtn")
        self.horizontalLayout.addWidget(self.cashAvailableBtn)
        self.goBackBtn = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goBackBtn.sizePolicy().hasHeightForWidth())
        self.goBackBtn.setSizePolicy(sizePolicy)
        self.goBackBtn.setMinimumSize(QtCore.QSize(260, 100))
        self.goBackBtn.setMaximumSize(QtCore.QSize(260, 100))
        self.goBackBtn.setStyleSheet("font: 75 35pt \"함초롬돋움\";")
        self.goBackBtn.setObjectName("goBackBtn")
        self.horizontalLayout.addWidget(self.goBackBtn)
        self.widget.raise_()
        self.layoutWidget.raise_()
        self.scrollArea.raise_()
        self.splitter_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tableBtn.setText(_translate("Form", "표"))
        self.graphBtn.setText(_translate("Form", "그래프"))
        self.dailySalesLabel.setText(_translate("Form", "일 매출"))
        self.wonLabel1.setText(_translate("Form", "원"))
        self.monthlySalesLabel.setText(_translate("Form", "월 매출"))
        self.wonLabel2.setText(_translate("Form", "원"))
        self.yearSalesLabel.setText(_translate("Form", "년 매출"))
        self.wonLabel3.setText(_translate("Form", "원"))
        self.chickenBtn.setText(_translate("Form", "치킨"))
        self.beverageBtn.setText(_translate("Form", "음료"))
        self.othersBtn.setText(_translate("Form", "기타"))
        self.timeLabel.setText(_translate("Form", "현재 시각: "))
        self.dateStatBtn.setText(_translate("Form", "날짜 별 통계"))
        self.productManagementBtn.setText(_translate("Form", "품목 관리"))
        self.cashAvailableBtn.setText(_translate("Form", "시재 관리"))
        self.goBackBtn.setText(_translate("Form", "돌아가기"))

